#!/usr/bin/env python3
"""Generate the Brio BOV website from bov-site.json.

Design is LOCKED to LAAA-Deploys/11168-camarillo-bov. The structure and the
stylesheet in template/ are Camarillo's, taken verbatim apart from the removal
of the PDF download button (Glen, 2026-07-30). Do not restyle here. If a value
looks wrong, fix bov-site.json and rebuild. Never hand-edit the output.

Emits real route files so every URL returns HTTP 200 on GitHub Pages with no
client-side routing:
    index.html
    359-parke/index.html
    1623-menlo/index.html
"""
import json, shutil
from html import escape
from pathlib import Path

ROOT = Path(__file__).parent
GENERATOR_VERSION = "bovsite-1.0.0"


# ---------------------------------------------------------------------------
# formatting helpers
# ---------------------------------------------------------------------------
def money(n, dp=0):
    if n is None:
        return "-"
    neg = n < 0
    s = f"${abs(n):,.{dp}f}"
    return f"({s})" if neg else s


def num(n, dp=0):
    return "-" if n is None else f"{n:,.{dp}f}"


def pct(n, dp=2):
    return "-" if n is None else f"{n:.{dp}f}%"


def e(s):
    return escape(str(s), quote=True)


def paras(items, cls=None):
    c = f' class="{cls}"' if cls else ""
    return "\n".join(f"<p{c}>{e(p)}</p>" for p in items)


def rel(path, depth):
    """Rewrite a root-relative asset path for a page nested `depth` levels down."""
    return ("../" * depth) + path if path else path


# ---------------------------------------------------------------------------
# shared blocks
# ---------------------------------------------------------------------------
def head(title, desc, data, d, canonical):
    dom = data["meta"]["domain"]
    og = f"https://{dom}/og.jpg"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="{e(desc)}">
<meta property="og:title" content="{e(title)}">
<meta property="og:description" content="{e(desc)}">
<meta property="og:image" content="{og}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:url" content="https://{dom}{canonical}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="LAAA Team">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{e(title)}">
<meta name="twitter:description" content="{e(desc)}">
<meta name="twitter:image" content="{og}">
<link rel="canonical" href="https://{dom}{canonical}">
<title>{e(title)}</title>
<link rel="icon" type="image/png" href="{rel('images/LAAA_Team_Blue.png', d)}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=DM+Serif+Display&display=swap" rel="stylesheet">
<style>
{(ROOT / 'template' / 'bov.css').read_text(encoding='utf-8')}
</style>
</head>
<body>
<!-- Generated by {GENERATOR_VERSION} from bov-site.json. Edits will be lost. Fix the data and rebuild. -->
"""


def cover(*, logo, label, title, address, stats, leads, client, month, hero, d):
    stat_html = "".join(
        f'<div class="cover-stat"><span class="cover-stat-value">{e(v)}</span>'
        f'<span class="cover-stat-label">{e(l)}</span></div>' for v, l in stats)
    head_html = "".join(
        f'<div class="cover-headshot-wrap"><img class="cover-headshot" src="{rel(a["headshot"], d)}" '
        f'alt="{e(a["name"])}"><div class="cover-headshot-name">{e(a["name"])}</div>'
        f'<div class="cover-headshot-title">{e(a["title"])}</div></div>' for a in leads)
    return f"""
<div class="cover">
  <div class="cover-bg" style="background-image:url('{rel(hero, d)}');"></div>
  <div class="cover-content">
    <img src="{rel(logo, d)}" class="cover-logo" alt="LAAA Team">
    <div class="cover-label">{e(label)}</div>
    <div class="cover-title">{e(title)}</div>
    <div class="cover-address">{e(address)}</div>
    <div class="gold-line" style="width:80px;margin:20px auto;"></div>
    <div class="cover-stats">{stat_html}</div>
    <div class="cover-headshots">{head_html}</div>
    <p class="client-greeting" id="client-greeting">Prepared Exclusively for {e(client)}</p>
    <p style="font-size:12px;color:rgba(255,255,255,0.55);margin-top:8px;">{e(month)}</p>
  </div>
</div>
"""


def toc(links, d):
    """links: list of (href, label). External hrefs are passed through."""
    out = []
    for href, label in links:
        h = href if href.startswith("#") else rel(href, d)
        out.append(f'<a href="{h}">{e(label)}</a>')
    return '<nav class="toc-nav" id="toc-nav">\n  ' + "\n  ".join(out) + "\n</nav>\n"


def section_head(title, subtitle):
    return (f'  <div class="section-title">{e(title)}</div>\n'
            f'  <div class="section-subtitle">{e(subtitle)}</div>\n'
            f'  <div class="section-divider"></div>\n')


def metrics4(items):
    return '  <div class="metrics-grid-4">' + "".join(
        f'<div class="metric-card"><span class="metric-value">{e(v)}</span>'
        f'<span class="metric-label">{e(l)}</span></div>' for v, l in items) + "</div>\n"


def track_record(data, d, prop=None):
    tr = data["track_record"]
    t = data["team"]
    # Three tiers, live from Airtable (Glen 2026-07-30): everything closed, then
    # this asset class, then THIS property's own market. The local tier uses the
    # subject's submarket where LAAA has depth there and a radius otherwise, and
    # the basis is always stated so the claim can never overreach.
    live = (data.get("stats") or {}).get("portfolio_track_record")
    lt = (prop or {}).get("track_record") or live
    if lt:
        local, basis = lt.get("local"), lt.get("local_basis") or {}
        cards = [(f"{lt['all']['count']}", "Closed Transactions"),
                 (f"{lt['asset_class']['count']}", "Apartment Sales")]
        if local:
            label = (f"in {basis['label']}" if basis.get("type") == "submarket"
                     else basis["label"].capitalize())
            cards.append((f"{local['count']}", label))
        else:
            cards.append((money(lt["asset_class"]["volume"] / 1e9, 2).replace("$", "$") + "B",
                          "Apartment Volume"))
        cards.append(("#1", "Most Active in LA County"))
        tr = dict(tr, metrics=cards)
    bios = "".join(
        f'<div class="bio-card"><img class="bio-headshot" src="{rel(a["headshot"], d)}" alt="{e(a["name"])}"><div>'
        f'<div class="bio-name">{e(a["name"])}</div><div class="bio-title">{e(a["title"])}</div>'
        f'<div class="bio-text">{e(a["bio"])}</div></div></div>' for a in t["leads"])
    grid = "".join(
        f'<div class="team-card"><img class="team-headshot" src="{rel(m["headshot"], d)}" alt="{e(m["name"])}">'
        f'<div class="team-card-name">{e(m["name"])}</div>'
        f'<div class="team-card-title">{e(m["title"])}</div></div>' for m in t["grid"])
    ach = "<br>\n      ".join(f"&bull; <strong>{e(a[0])}</strong> - {e(a[1])}" for a in tr["achievements"])
    press = "".join(f'<span class="press-logo">{e(p)}</span>' for p in tr["press"])
    return f"""
<div class="section section-alt" id="track-record">
{section_head("Team Track Record", "LA Apartment Advisors at Marcus & Millichap")}\
  <div class="tr-tagline"><span style="display:block;font-size:1.1em;font-weight:700;margin-bottom:4px;">LAAA Team of Marcus &amp; Millichap</span>Expertise, Execution, Excellence.</div>
{metrics4(tr["metrics"])}\
  <div class="tr-map-print"><img src="{rel('images/maps-portfolio-subjects.png', d)}" alt="LAAA Portfolio Map" loading="lazy"></div>
  <div class="tr-service-quote">
    <h3>"We Didn't Invent Great Service, We Just Work Relentlessly to Provide It."</h3>
{paras(tr["narrative"])}
  </div>
</div>

<div class="section tr-page2">
  <div style="text-align:center;"><div class="section-title" style="margin-bottom:4px;">Our Team</div><div class="section-divider" style="margin:0 auto 16px;"></div></div>
  <div class="costar-badge">
    <div class="costar-badge-title">#1 Most Active Multifamily Sales Team in LA County</div>
    <div class="costar-badge-sub">CoStar &bull; 2019, 2020, 2021 &bull; #4 in California</div>
  </div>
  <div class="bio-grid">{bios}</div>
  <div class="team-grid">{grid}</div>
  <div class="condition-note"><div class="condition-note-label">Key Achievements</div>
    <p class="achievements-list">
      {ach}
    </p></div>
  <div class="press-strip"><span class="press-strip-label">As Featured In</span>{press}</div>
</div>
"""


def marketing(data):
    m = data["marketing"]
    chan = "".join(f"<li><strong>{e(c[0])}</strong> - {e(c[1])}</li>" for c in m["channels"])

    # Live Mailchimp figures. Nothing here is hardcoded: the 2026-07-30 build
    # shipped 23,795 subscribers and a 26.1% open rate copied from another deal
    # and both were wrong. Opens are Mailchimp's proxy-excluded count, so machine
    # opens from Apple Mail Privacy are already removed.
    mk = (data.get("stats") or {}).get("marketing")
    split = ""
    if mk:
        pl = mk["per_launch"]
        cards = [(f"{mk['subscribers']:,}", "Investors Reached"),
                 (f"{mk['brokers']:,}", "Cooperating Brokers"),
                 (f"{pl['opens_verified']:,}", "Verified Opens per Launch"),
                 (f"{pl['property_page_clicks']:,}", "Clicked to the Property")]
        m = dict(m, metrics=cards)
        # "Clients" is the INTERNAL segment name and must never appear here.
        split = (f'  <p class="narrative" style="margin-top:-6px;">Of the {mk["subscribers"]:,} investors on our '
                 f'list, {mk["brokers"]:,} are cooperating brokers, {mk["principals"]:,} are principals and '
                 f'property owners, and {mk["developers"]:,} are developers. Every launch reaches all of them '
                 f'the same day.</p>\n')

    proactive = """
  <h3 class="sub-heading">How We Find Your Buyer</h3>
  <div class="inv-text">
    <p>Most brokers are reactive. They post the listing, run an email blast, and wait for the phone to ring. We do all of that, and we do it well. Then we do the part almost nobody does. We pick up the phone.</p>
    <p>Before your building goes to market, our system builds a probable buyer list for it specifically. It pulls the county assessment record for every property in the surrounding area: who owns it, where their mail goes, what they paid, when they bought, who financed it, and how many other buildings they hold. Out of that come the three groups most likely to buy your building. Owners of comparable product nearby. Buyers who have closed on buildings like yours recently. Exchange buyers with money that has to be placed on a deadline.</p>
    <p><strong>That list runs well over 100 names, and we call every one of them.</strong></p>
    <p>This is a proven system and we built it ourselves. It is not a Marcus &amp; Millichap product and it did not come with the brand. Our team designed it, we own it, and we use it on every listing we take.</p>
    <p>Sitting on top of it is the part software cannot buy. Careers spanning 20 years of notes on these same buyers. We have their direct numbers and their emails. We know what they bought last, what they passed on and why, and what they are hunting for now. Every seller we take on inherits all of it on day one.</p>
    <p>Then we work it. Buyer lists, offer matrices, and a straight answer every week on who called, who toured, and what they said.</p>
  </div>
"""
    return f"""
<div class="page-break-marker"></div>
<div class="section" id="marketing">
{section_head("Our Marketing Approach & Reach", "Every Active LA Multifamily Buyer, Within Days of Launch")}\
{metrics4(m["metrics"])}\
{split}\
  <div class="mkt-quote">"We are PROACTIVE marketers, not reactive."</div>
{proactive}\
  <div class="inv-highlights"><h4>How We Reach the Market</h4><ul>{chan}</ul></div>
{paras(m["narrative"], "narrative")}
</div>
"""


def footer(data, d):
    people = "".join(
        f'<div class="footer-person"><img src="{rel(a["headshot"], d)}" class="footer-headshot" alt="{e(a["name"])}">'
        f'<div class="footer-name">{e(a["name"])}</div><div class="footer-title">{e(a["title"])}</div>'
        f'<div class="footer-contact"><a href="tel:{a["tel"]}">{e(a["phone"])}</a><br>'
        f'<a href="mailto:{a["email"]}">{e(a["email"])}</a><br>{e(a["license"])}</div></div>'
        for a in data["team"]["leads"])
    return f"""
<div class="footer" id="contact">
  <img src="{rel('images/LAAA_Team_White.png', d)}" class="footer-logo" alt="LAAA Team">
  <div class="footer-team">{people}</div>
  <div class="footer-office">16830 Ventura Blvd, Ste. 100, Encino, CA 91436 | <a href="https://www.laaa.com" target="_blank" rel="noopener" style="color:inherit;text-decoration:none;">www.laaa.com</a></div>
  <div class="footer-disclaimer">This information has been secured from sources we believe to be reliable, but we make no representations or warranties, expressed or implied, as to the accuracy of the information. Buyer must verify the information and bears all risk for any inaccuracies. Marcus &amp; Millichap Real Estate Investment Services, Inc. | License: CA 01930580.</div>
</div>
"""


NAV_JS = """
var params = new URLSearchParams(window.location.search);
var client = params.get('client');
if (client) { var el = document.getElementById('client-greeting'); if (el) el.textContent = 'Prepared Exclusively for ' + client; }
var navWrap = document.getElementById('toc-nav');
document.querySelectorAll('.toc-nav a[href^="#"]').forEach(function(link) {
  link.addEventListener('click', function(ev) {
    ev.preventDefault();
    var target = document.querySelector(this.getAttribute('href'));
    if (target) { var nh = navWrap.offsetHeight; window.scrollTo({ top: target.getBoundingClientRect().top + window.pageYOffset - nh - 4, behavior: 'smooth' }); }
  });
});
var tocLinks = document.querySelectorAll('.toc-nav a[href^="#"]'); var tocSections = [];
tocLinks.forEach(function(link) { var s = document.getElementById(link.getAttribute('href').substring(1)); if (s) tocSections.push({ link: link, section: s }); });
function updateActiveTocLink() {
  if (!navWrap) return;
  var nh = navWrap.offsetHeight + 20; var sp = window.pageYOffset + nh; var cur = null;
  tocSections.forEach(function(it) { if (it.section.offsetTop <= sp) cur = it.link; });
  tocLinks.forEach(function(l) { l.classList.remove('toc-active'); });
  if (cur) {
    cur.classList.add('toc-active');
    /* keep the active link visible in the scrolling nav on phones */
    var lr = cur.getBoundingClientRect(), nr = navWrap.getBoundingClientRect();
    if (lr.left < nr.left || lr.right > nr.right) {
      navWrap.scrollTo({ left: cur.offsetLeft - (navWrap.clientWidth / 2) + (cur.offsetWidth / 2), behavior: 'smooth' });
    }
  }
}
window.addEventListener('scroll', updateActiveTocLink); updateActiveTocLink();
"""

SLIDE_JS = """
var slideIdx = 0;
function _gid(id){ return document.getElementById(id); }
function renderThumbs(){
  var t = _gid('slideThumbs'); if(!t) return; t.innerHTML = '';
  SLIDES.forEach(function(s, i){
    var im = document.createElement('img');
    im.src = s[0]; im.alt = s[1]; im.loading = 'lazy';
    im.onclick = function(){ slideShow(i); };
    t.appendChild(im);
  });
}
function slideShow(i){
  slideIdx = (i + SLIDES.length) % SLIDES.length;
  var m = _gid('slideMain'); if(m){ m.src = SLIDES[slideIdx][0]; m.alt = SLIDES[slideIdx][1]; }
  var c = _gid('slideCaption'); if(c){ c.innerHTML = SLIDES[slideIdx][1]; }
  var n = _gid('slideCounter'); if(n){ n.textContent = (slideIdx+1) + ' / ' + SLIDES.length; }
  var thumbs = _gid('slideThumbs');
  if(thumbs){ Array.prototype.forEach.call(thumbs.children, function(ch, j){ ch.className = (j===slideIdx ? 'active' : ''); }); }
  if(_gid('lightbox') && _gid('lightbox').classList.contains('open')) syncLightbox();
}
function slideMove(dir){ slideShow(slideIdx + dir); }
function openLightbox(){ var lb=_gid('lightbox'); if(lb){ lb.classList.add('open'); syncLightbox(); } }
function closeLightbox(){ var lb=_gid('lightbox'); if(lb) lb.classList.remove('open'); }
function syncLightbox(){ var im=_gid('lbImg'), cp=_gid('lbCap'); if(im) im.src=SLIDES[slideIdx][0]; if(cp) cp.innerHTML=SLIDES[slideIdx][1]; }
document.addEventListener('keydown', function(ev){
  var lb=_gid('lightbox'); if(lb && lb.classList.contains('open')){
    if(ev.key==='Escape') closeLightbox();
    else if(ev.key==='ArrowLeft') slideMove(-1);
    else if(ev.key==='ArrowRight') slideMove(1);
  }
});
renderThumbs(); slideShow(0);
"""
